[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#1428A0"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F7FB"
textColor = "#111827"
